-- Seeds the question bank drafted in question-bank/questions-draft-v2.md:
-- 399 new questions across General (HireVue-tagged + plain general
-- behavioral), and Finance sub-industries (Investment Banking, Private
-- Equity, Consulting), each split behavioral/technical and
-- easy/medium/hard. 3 questions that exact-duplicated existing rows
-- (e.g. "Tell me about yourself.") were skipped.

insert into public.questions (text, category, difficulty, industries, tags) values
('Walk me through your background in a couple of minutes.', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('Give me a quick summary of who you are, professionally.', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('What are your long-term career goals?', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('Where do you want your career to be headed five or ten years from now?', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('What kind of work do you want to be doing later in your career?', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('Why are you interested in this company?', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('What drew you to apply here specifically?', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('What do you know about us, and why does it appeal to you?', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('What would you say is your biggest strength?', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('What''s the skill you''d point to first if someone asked what you''re best at?', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('What do people usually compliment you on at work or school?', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('What''s one thing you''re working on improving about yourself?', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('What''s an area of your work you''re actively trying to get better at?', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('If you had to name a weakness, what would it be?', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('What do you like to do outside of school or work?', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('How do you spend your time when you''re not working or studying?', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('Tell me about a hobby or interest that isn''t on your resume.', 'behavioral', 'easy', '{"general"}', '{"hirevue"}'),
('Tell me about a time you had to work with someone whose style was very different from yours.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Describe a time you partnered with someone who approached problems completely differently than you do.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Tell me about working with a teammate you didn''t naturally click with.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Describe a moment when you didn''t have enough information to complete a task. What did you do?', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Tell me about a time you had to make progress on something despite missing key details.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Walk me through a situation where you had to fill in gaps with your own judgment.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Tell me about a time you had to stay calm under a tight deadline.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Describe a moment when everything felt like it was due at once. How did you get through it?', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Tell me about handling pressure when there wasn''t much time to think.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Walk me through a time you disagreed with a decision your team made.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Tell me about a call your group made that you didn''t personally agree with.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Describe a time you voiced a different opinion than the rest of your team.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Describe a situation where you had to learn something new very quickly.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Tell me about picking up a skill on short notice because you had no choice.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Walk me through a time you were thrown into something unfamiliar and had to adapt fast.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('What''s a piece of feedback that changed how you work?', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Tell me about feedback that actually shifted your approach afterward.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Describe a comment or critique that stuck with you and changed your habits.', 'behavioral', 'medium', '{"general"}', '{"hirevue"}'),
('Tell me about the last time you let a teammate down. What would you do differently now?', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('Describe a moment you didn''t come through for someone who was counting on you.', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('Walk me through a time your absence or mistake put a colleague in a tough spot.', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('Describe a time a plan you were responsible for fell apart. How did you handle it in the moment?', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('Tell me about something you owned that collapsed partway through. What did you do right then?', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('Walk me through a project of yours that went sideways, and your first move when it did.', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('Tell me about a time you had to deliver bad news to someone who wasn''t expecting it.', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('Describe a conversation where you had to tell someone something they really didn''t want to hear.', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('Walk me through breaking unwelcome news to a group that was counting on a different outcome.', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('What''s the most significant mistake you''ve made professionally, and what changed afterward?', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('Tell me about your biggest career misstep so far and what it taught you.', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('Describe an error early in your career that still shapes how you work today.', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('Tell me about a time your judgment was wrong and you found out the hard way.', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('Describe a decision that felt right at the time but turned out to be a mistake.', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('Walk me through a call you made that you''d take back if you could.', 'behavioral', 'hard', '{"general"}', '{"hirevue"}'),
('What tools or software do you rely on most day-to-day, and why?', 'technical', 'easy', '{"general"}', '{"hirevue"}'),
('Which apps or platforms do you consider essential to how you work?', 'technical', 'easy', '{"general"}', '{"hirevue"}'),
('What''s in your everyday toolkit, and what would you struggle without?', 'technical', 'easy', '{"general"}', '{"hirevue"}'),
('Walk me through a project you''ve built or contributed to from start to finish.', 'technical', 'easy', '{"general"}', '{"hirevue"}'),
('Pick one project you''re proud of and walk me through how it came together.', 'technical', 'easy', '{"general"}', '{"hirevue"}'),
('Describe something you built, end to end, and your role in it.', 'technical', 'easy', '{"general"}', '{"hirevue"}'),
('How do you decide which programming language or tool fits a given task?', 'technical', 'easy', '{"general"}', '{"hirevue"}'),
('When you''re starting something new, how do you choose the right tool for the job?', 'technical', 'easy', '{"general"}', '{"hirevue"}'),
('Walk me through your thought process for picking an approach or platform for a new task.', 'technical', 'easy', '{"general"}', '{"hirevue"}'),
('Explain a technical concept from your field to someone with no background in it.', 'technical', 'medium', '{"general"}', '{"hirevue"}'),
('Pick something technical you understand well and explain it like I''m a complete beginner.', 'technical', 'medium', '{"general"}', '{"hirevue"}'),
('Describe a complex idea from your work in terms a non-expert would follow.', 'technical', 'medium', '{"general"}', '{"hirevue"}'),
('Walk me through how you''d debug a system that suddenly stopped working.', 'technical', 'medium', '{"general"}', '{"hirevue"}'),
('Something breaks with no warning and no error message — what''s your first move?', 'technical', 'medium', '{"general"}', '{"hirevue"}'),
('Describe your process for tracking down the cause of an unexpected failure.', 'technical', 'medium', '{"general"}', '{"hirevue"}'),
('Describe how you approach learning a new tool or technology on your own.', 'technical', 'medium', '{"general"}', '{"hirevue"}'),
('Walk me through how you taught yourself a skill nobody showed you directly.', 'technical', 'medium', '{"general"}', '{"hirevue"}'),
('Tell me about picking up a new technical skill without formal instruction.', 'technical', 'medium', '{"general"}', '{"hirevue"}'),
('Tell me about the most difficult technical problem you''ve solved, and where you got stuck along the way.', 'technical', 'hard', '{"general"}', '{"hirevue"}'),
('Walk me through your hardest technical challenge, including the point where you almost gave up.', 'technical', 'hard', '{"general"}', '{"hirevue"}'),
('Describe the toughest bug or issue you''ve dealt with and what finally cracked it.', 'technical', 'hard', '{"general"}', '{"hirevue"}'),
('Describe a time your technical solution to a problem turned out to be wrong. How did you find out, and what did you do?', 'technical', 'hard', '{"general"}', '{"hirevue"}'),
('Tell me about a fix you shipped that didn''t actually solve the underlying problem.', 'technical', 'hard', '{"general"}', '{"hirevue"}'),
('Walk me through a time your approach looked right but wasn''t, and how you caught it.', 'technical', 'hard', '{"general"}', '{"hirevue"}'),
('Walk me through a project where the requirements changed significantly after you''d already started building.', 'technical', 'hard', '{"general"}', '{"hirevue"}'),
('Describe building something, then having the goalposts move halfway through.', 'technical', 'hard', '{"general"}', '{"hirevue"}'),
('Tell me about adapting a project mid-stream when the original plan no longer made sense.', 'technical', 'hard', '{"general"}', '{"hirevue"}'),
('What makes this company stand out to you compared to others you''ve looked at?', 'behavioral', 'easy', '{"general"}', '{}'),
('What about this opportunity got you to apply?', 'behavioral', 'easy', '{"general"}', '{}'),
('What''s your greatest strength, and how have you used it?', 'behavioral', 'easy', '{"general"}', '{}'),
('Tell me about the strength you''d lead with and a time it actually mattered.', 'behavioral', 'easy', '{"general"}', '{}'),
('What ability of yours has consistently paid off for you?', 'behavioral', 'easy', '{"general"}', '{}'),
('Where do you want to be in five years?', 'behavioral', 'easy', '{"general"}', '{}'),
('What does your ideal career look like a few years from now?', 'behavioral', 'easy', '{"general"}', '{}'),
('How do you picture your role evolving over the next several years?', 'behavioral', 'easy', '{"general"}', '{}'),
('Why are you looking to leave your current role?', 'behavioral', 'easy', '{"general"}', '{}'),
('What''s prompting you to make a change right now?', 'behavioral', 'easy', '{"general"}', '{}'),
('What''s missing from where you are that you''re hoping to find here?', 'behavioral', 'easy', '{"general"}', '{}'),
('What motivates you to do good work?', 'behavioral', 'easy', '{"general"}', '{}'),
('What keeps you engaged and putting in real effort?', 'behavioral', 'easy', '{"general"}', '{}'),
('What gets you excited to show up and do well?', 'behavioral', 'easy', '{"general"}', '{}'),
('Tell me about a time you worked well as part of a team.', 'behavioral', 'easy', '{"general"}', '{}'),
('Describe a team experience that went really smoothly and why.', 'behavioral', 'easy', '{"general"}', '{}'),
('Walk me through a group effort you''d point to as a good example of teamwork.', 'behavioral', 'easy', '{"general"}', '{}'),
('What kind of work environment brings out your best?', 'behavioral', 'easy', '{"general"}', '{}'),
('Describe the setting where you feel most productive.', 'behavioral', 'easy', '{"general"}', '{}'),
('What conditions help you do your best work?', 'behavioral', 'easy', '{"general"}', '{}'),
('Do you have any questions for me?', 'behavioral', 'easy', '{"general"}', '{}'),
('What would you like to know about the role or the team?', 'behavioral', 'easy', '{"general"}', '{}'),
('Is there anything I can clarify about the position?', 'behavioral', 'easy', '{"general"}', '{}'),
('Describe a time you had to manage several competing priorities at once. How did you decide what came first?', 'behavioral', 'medium', '{"general"}', '{}'),
('Tell me about juggling multiple urgent things simultaneously and how you triaged them.', 'behavioral', 'medium', '{"general"}', '{}'),
('Walk me through a period where everything felt equally important and you had to pick an order anyway.', 'behavioral', 'medium', '{"general"}', '{}'),
('Tell me about a goal that took real effort to reach. What made it hard, and how did you get there?', 'behavioral', 'medium', '{"general"}', '{}'),
('Describe an accomplishment that didn''t come easily, and what got you through the hard part.', 'behavioral', 'medium', '{"general"}', '{}'),
('Walk me through a goal you almost didn''t hit, and what changed the outcome.', 'behavioral', 'medium', '{"general"}', '{}'),
('Describe a time you had to give a colleague feedback they didn''t want to hear.', 'behavioral', 'medium', '{"general"}', '{}'),
('Tell me about delivering criticism to someone who wasn''t expecting it.', 'behavioral', 'medium', '{"general"}', '{}'),
('Walk me through a tough conversation you had to initiate with a peer.', 'behavioral', 'medium', '{"general"}', '{}'),
('Tell me about a time you had to adjust quickly to a major change at work or school.', 'behavioral', 'medium', '{"general"}', '{}'),
('Describe adapting when the rules or plan changed with little warning.', 'behavioral', 'medium', '{"general"}', '{}'),
('Walk me through handling a sudden shift you had no control over.', 'behavioral', 'medium', '{"general"}', '{}'),
('Walk me through a time you took the lead on something without being asked to.', 'behavioral', 'medium', '{"general"}', '{}'),
('Describe stepping up before anyone told you to.', 'behavioral', 'medium', '{"general"}', '{}'),
('Tell me about a moment you took ownership of a problem that wasn''t technically yours.', 'behavioral', 'medium', '{"general"}', '{}'),
('Describe a time a team you were part of didn''t deliver what it was supposed to. What happened?', 'behavioral', 'medium', '{"general"}', '{}'),
('Tell me about a group effort that missed its target, and your role in the fallout.', 'behavioral', 'medium', '{"general"}', '{}'),
('Walk me through a project that came up short of expectations.', 'behavioral', 'medium', '{"general"}', '{}'),
('Tell me about a customer, client, or classmate you had a hard time satisfying, and how you handled it.', 'behavioral', 'medium', '{"general"}', '{}'),
('Describe dealing with someone who was genuinely difficult to please.', 'behavioral', 'medium', '{"general"}', '{}'),
('Walk me through defusing a frustrated person you were responsible for helping.', 'behavioral', 'medium', '{"general"}', '{}'),
('How do you keep yourself organized when you have a lot on your plate?', 'behavioral', 'medium', '{"general"}', '{}'),
('Walk me through your system for staying on top of a heavy workload.', 'behavioral', 'medium', '{"general"}', '{}'),
('Describe how you avoid letting things slip when you''re overloaded.', 'behavioral', 'medium', '{"general"}', '{}'),
('What''s the toughest piece of feedback you''ve ever received, and do you agree with it?', 'behavioral', 'hard', '{"general"}', '{}'),
('Tell me about the harshest criticism you''ve gotten and whether you think it was fair.', 'behavioral', 'hard', '{"general"}', '{}'),
('Describe feedback that stung specifically because it was accurate.', 'behavioral', 'hard', '{"general"}', '{}'),
('Tell me about a time you completely changed your position on something important after being challenged.', 'behavioral', 'hard', '{"general"}', '{}'),
('Describe a moment someone talked you out of a firmly held view.', 'behavioral', 'hard', '{"general"}', '{}'),
('Walk me through reversing a decision after new information changed your mind.', 'behavioral', 'hard', '{"general"}', '{}'),
('Describe a time you had to go along with a decision you personally disagreed with.', 'behavioral', 'hard', '{"general"}', '{}'),
('Tell me about executing a plan you thought was the wrong call.', 'behavioral', 'hard', '{"general"}', '{}'),
('Walk me through supporting a decision in public that you''d argued against in private.', 'behavioral', 'hard', '{"general"}', '{}'),
('If I called your last manager or professor right now, what would they say your biggest weakness is?', 'behavioral', 'hard', '{"general"}', '{}'),
('What would your last supervisor say is the one thing holding you back?', 'behavioral', 'hard', '{"general"}', '{}'),
('Guess what a former boss would flag as your main area for growth.', 'behavioral', 'hard', '{"general"}', '{}'),
('Tell me about a time your work was criticized in front of other people.', 'behavioral', 'hard', '{"general"}', '{}'),
('Describe being called out publicly for something that wasn''t your best work.', 'behavioral', 'hard', '{"general"}', '{}'),
('Walk me through a moment your performance was questioned in a group setting.', 'behavioral', 'hard', '{"general"}', '{}'),
('What''s something you''re genuinely insecure about in your professional abilities?', 'behavioral', 'hard', '{"general"}', '{}'),
('What professional skill do you wish you were more confident in?', 'behavioral', 'hard', '{"general"}', '{}'),
('Where do you privately doubt yourself the most at work?', 'behavioral', 'hard', '{"general"}', '{}'),
('Sell me on something ordinary — a stapler, a pencil, this chair — in under a minute.', 'behavioral', 'hard', '{"general"}', '{}'),
('Convince me to buy something completely mundane in 60 seconds.', 'behavioral', 'hard', '{"general"}', '{}'),
('Pitch me on an everyday object like it''s the best product on the market.', 'behavioral', 'hard', '{"general"}', '{}'),
('Tell me about a time you had to defend a position that most people around you disagreed with.', 'behavioral', 'hard', '{"general"}', '{}'),
('Describe standing by an unpopular opinion in a group setting.', 'behavioral', 'hard', '{"general"}', '{}'),
('Walk me through a time you were the lone dissenting voice and stuck with it.', 'behavioral', 'hard', '{"general"}', '{}'),
('Take me through your background chronologically, focusing on what led you here.', 'behavioral', 'easy', '{"ib"}', '{}'),
('Give me the two-minute version of your resume, highlighting what''s relevant to this role.', 'behavioral', 'easy', '{"ib"}', '{}'),
('Why investment banking, specifically, over other finance careers?', 'behavioral', 'easy', '{"ib"}', '{}'),
('What makes banking the right fit for you versus private equity, consulting, or corporate finance?', 'behavioral', 'easy', '{"ib"}', '{}'),
('Of all the paths into finance, why did you land on this one?', 'behavioral', 'easy', '{"ib"}', '{}'),
('Why our firm, and not one of our competitors?', 'behavioral', 'easy', '{"ib"}', '{}'),
('What made you target us specifically within the industry?', 'behavioral', 'easy', '{"ib"}', '{}'),
('What do you know about our firm that made you want to apply here over other banks?', 'behavioral', 'easy', '{"ib"}', '{}'),
('What are your biggest strengths and weaknesses for this role?', 'behavioral', 'easy', '{"ib"}', '{}'),
('Where do you feel strongest going into this job, and where are you weakest?', 'behavioral', 'easy', '{"ib"}', '{}'),
('What would you want your future analyst class to know about your strengths and blind spots?', 'behavioral', 'easy', '{"ib"}', '{}'),
('What do you think a first-year analyst actually does day to day?', 'behavioral', 'easy', '{"ib"}', '{}'),
('Walk me through what you expect this job to actually look like once you start.', 'behavioral', 'easy', '{"ib"}', '{}'),
('What''s your understanding of the day-to-day workload in this seat?', 'behavioral', 'easy', '{"ib"}', '{}'),
('Tell me about a group project where you had to hit a hard deadline with limited resources.', 'behavioral', 'medium', '{"ib"}', '{}'),
('Describe delivering something on time despite not having what you needed to do it comfortably.', 'behavioral', 'medium', '{"ib"}', '{}'),
('Walk me through a crunch-time project and how your team pulled it off.', 'behavioral', 'medium', '{"ib"}', '{}'),
('Describe a time you disagreed with a teammate about the right way to approach a task. What happened?', 'behavioral', 'medium', '{"ib"}', '{}'),
('Tell me about a real disagreement over process, not just outcome, with someone on your team.', 'behavioral', 'medium', '{"ib"}', '{}'),
('Walk me through a moment you and a collaborator saw a problem completely differently.', 'behavioral', 'medium', '{"ib"}', '{}'),
('How committed are you to this path if the hours turn out to be as bad as people say?', 'behavioral', 'medium', '{"ib"}', '{}'),
('What happens to your motivation on the nights this job is genuinely brutal?', 'behavioral', 'medium', '{"ib"}', '{}'),
('Convince me you''ll still want this job after your first miserable all-nighter.', 'behavioral', 'medium', '{"ib"}', '{}'),
('Which groups or industries within the firm are you most drawn to, and why?', 'behavioral', 'medium', '{"ib"}', '{}'),
('If you could pick any group here to start in, which would it be and why?', 'behavioral', 'medium', '{"ib"}', '{}'),
('Talk me through the coverage or product groups that interest you most and what''s behind that interest.', 'behavioral', 'medium', '{"ib"}', '{}'),
('You don''t have direct finance experience — what makes you confident you can handle the technical side of this job?', 'behavioral', 'medium', '{"ib"}', '{}'),
('Given your background isn''t finance-heavy, why should I trust you''ll pick up the technical skills quickly?', 'behavioral', 'medium', '{"ib"}', '{}'),
('What have you done outside your coursework to prepare for the technical demands of this role?', 'behavioral', 'medium', '{"ib"}', '{}'),
('Tell me about the most difficult decision you''ve made as part of a team, and what you''d change in hindsight.', 'behavioral', 'medium', '{"ib"}', '{}'),
('Describe a group decision you were part of that you''d handle differently today.', 'behavioral', 'medium', '{"ib"}', '{}'),
('Walk me through a tough call your team made and how it played out.', 'behavioral', 'medium', '{"ib"}', '{}'),
('Walk me through a time you were the reason something at work or school didn''t go as planned.', 'behavioral', 'hard', '{"ib"}', '{}'),
('Tell me about an outcome that went wrong specifically because of something you did or didn''t do.', 'behavioral', 'hard', '{"ib"}', '{}'),
('Describe a failure you were personally responsible for, not just present for.', 'behavioral', 'hard', '{"ib"}', '{}'),
('If you already interned somewhere adjacent to this industry, why didn''t you get a return offer — or why didn''t you take one?', 'behavioral', 'hard', '{"ib"}', '{}'),
('Walk me through what happened with your last relevant internship and why you''re not going back.', 'behavioral', 'hard', '{"ib"}', '{}'),
('Explain the gap between your last internship and this application.', 'behavioral', 'hard', '{"ib"}', '{}'),
('You took time in a different field before applying here. Convince me this isn''t just a backup plan.', 'behavioral', 'hard', '{"ib"}', '{}'),
('Why should I believe this career switch is genuine and not just a fallback?', 'behavioral', 'hard', '{"ib"}', '{}'),
('Make the case that your unconventional path makes you a better candidate, not a riskier one.', 'behavioral', 'hard', '{"ib"}', '{}'),
('What''s a real weakness of yours that would concern me if I hired you for this specific job?', 'behavioral', 'hard', '{"ib"}', '{}'),
('Tell me the honest downside of hiring you, specifically for this seat.', 'behavioral', 'hard', '{"ib"}', '{}'),
('What''s the one thing about you that should give me pause before extending an offer?', 'behavioral', 'hard', '{"ib"}', '{}'),
('Tell me about a time you had to push back on someone more senior than you. How did it go?', 'behavioral', 'hard', '{"ib"}', '{}'),
('Describe disagreeing with someone who had far more authority than you in the room.', 'behavioral', 'hard', '{"ib"}', '{}'),
('Walk me through challenging a superior''s call and what the outcome was.', 'behavioral', 'hard', '{"ib"}', '{}'),
('Give me a specific example of when you found and flagged a mistake nobody else on the team had caught.', 'behavioral', 'hard', '{"ib"}', '{}'),
('Tell me about catching an error that would have slipped through if not for you.', 'behavioral', 'hard', '{"ib"}', '{}'),
('Describe a time your attention to detail prevented a real problem.', 'behavioral', 'hard', '{"ib"}', '{}'),
('What are the three core financial statements, and what does each one tell you?', 'technical', 'easy', '{"ib"}', '{}'),
('Name the three financial statements and describe, in one sentence each, what they show.', 'technical', 'easy', '{"ib"}', '{}'),
('Walk me through what the income statement, balance sheet, and cash flow statement each measure.', 'technical', 'easy', '{"ib"}', '{}'),
('What''s the difference between Enterprise Value and Equity Value?', 'technical', 'easy', '{"ib"}', '{}'),
('Explain Enterprise Value versus Equity Value the way you''d explain it to a friend outside finance.', 'technical', 'easy', '{"ib"}', '{}'),
('If a company has debt and cash on its balance sheet, how does that affect the gap between its Equity Value and Enterprise Value?', 'technical', 'easy', '{"ib"}', '{}'),
('In plain terms, what does the time value of money mean?', 'technical', 'easy', '{"ib"}', '{}'),
('Why is a dollar today worth more than a dollar a year from now?', 'technical', 'easy', '{"ib"}', '{}'),
('Explain the core idea behind discounting future cash flows.', 'technical', 'easy', '{"ib"}', '{}'),
('What is EBITDA, and why do people use it instead of net income?', 'technical', 'easy', '{"ib"}', '{}'),
('Walk me through what EBITDA strips out of net income and why that''s useful for comparing companies.', 'technical', 'easy', '{"ib"}', '{}'),
('Why might two companies with similar revenue have very different net income but similar EBITDA?', 'technical', 'easy', '{"ib"}', '{}'),
('Why would a company be worth more to a strategic acquirer than to a financial buyer?', 'technical', 'easy', '{"ib"}', '{}'),
('What kinds of value can a strategic buyer capture that a private equity firm typically can''t?', 'technical', 'easy', '{"ib"}', '{}'),
('Explain why synergies matter more to one type of buyer than another.', 'technical', 'easy', '{"ib"}', '{}'),
('What''s the difference between accounts receivable and accounts payable?', 'technical', 'easy', '{"ib"}', '{}'),
('Explain, with a simple example, how AR and AP show up differently on the balance sheet.', 'technical', 'easy', '{"ib"}', '{}'),
('If a company''s accounts receivable balance grows, what does that tell you about its cash collection?', 'technical', 'easy', '{"ib"}', '{}'),
('Walk me through how the three financial statements connect to one another.', 'technical', 'medium', '{"ib"}', '{}'),
('If net income increases by $10, trace how that flows through the other two statements.', 'technical', 'medium', '{"ib"}', '{}'),
('Explain the linkages between the income statement, balance sheet, and cash flow statement using a real example.', 'technical', 'medium', '{"ib"}', '{}'),
('A company buys a piece of equipment for cash. How does that flow through all three statements?', 'technical', 'medium', '{"ib"}', '{}'),
('Walk me through the full statement impact of purchasing $50 of inventory on credit.', 'technical', 'medium', '{"ib"}', '{}'),
('A company takes out a loan to fund a new project. Trace that transaction through all three statements.', 'technical', 'medium', '{"ib"}', '{}'),
('What''s the difference between unlevered and levered free cash flow, and when would you use each?', 'technical', 'medium', '{"ib"}', '{}'),
('Explain why a DCF built off unlevered free cash flow needs to be discounted differently than one using levered free cash flow.', 'technical', 'medium', '{"ib"}', '{}'),
('Walk me through how you''d convert Net Income into Unlevered Free Cash Flow.', 'technical', 'medium', '{"ib"}', '{}'),
('Explain how you''d build out a basic DCF, step by step.', 'technical', 'medium', '{"ib"}', '{}'),
('Walk me through the core building blocks of a DCF from projecting cash flows to arriving at a value.', 'technical', 'medium', '{"ib"}', '{}'),
('If you only had 60 seconds, how would you summarize what a DCF actually does?', 'technical', 'medium', '{"ib"}', '{}'),
('What is WACC, and intuitively, why does it matter for valuation?', 'technical', 'medium', '{"ib"}', '{}'),
('Explain what the "weighted" part of WACC actually refers to.', 'technical', 'medium', '{"ib"}', '{}'),
('Why does a company''s WACC change if its mix of debt and equity changes?', 'technical', 'medium', '{"ib"}', '{}'),
('Walk me through the three most common valuation methodologies, and one advantage and disadvantage of each.', 'technical', 'medium', '{"ib"}', '{}'),
('Compare Comparable Companies, Precedent Transactions, and DCF — where does each tend to over- or under-value a business?', 'technical', 'medium', '{"ib"}', '{}'),
('If you had to pick just one valuation method under time pressure, which would you choose and why?', 'technical', 'medium', '{"ib"}', '{}'),
('What happens to Goodwill on the balance sheet after an acquisition?', 'technical', 'medium', '{"ib"}', '{}'),
('Explain where Goodwill comes from and what it represents economically.', 'technical', 'medium', '{"ib"}', '{}'),
('If an acquirer overpays for a target, how does that show up in the financial statements afterward?', 'technical', 'medium', '{"ib"}', '{}'),
('Why might two companies with the same Enterprise Value have very different Equity Values?', 'technical', 'medium', '{"ib"}', '{}'),
('Explain how differing capital structures can produce identical Enterprise Values but very different Equity Values.', 'technical', 'medium', '{"ib"}', '{}'),
('Two companies generate the same operating cash flow but have very different debt loads. How does that affect their relative Equity Values?', 'technical', 'medium', '{"ib"}', '{}'),
('Walk me through how you''d calculate Terminal Value in a DCF, and defend which method you''d use and why.', 'technical', 'hard', '{"ib"}', '{}'),
('Compare the Gordon Growth method and the Exit Multiple method for Terminal Value, and explain when each is more appropriate.', 'technical', 'hard', '{"ib"}', '{}'),
('A DCF''s Terminal Value ends up being 80% of the total valuation. Is that a red flag, and how would you sanity-check it?', 'technical', 'hard', '{"ib"}', '{}'),
('A deal is funded with 100% stock. Under what conditions would that deal be accretive versus dilutive to EPS?', 'technical', 'hard', '{"ib"}', '{}'),
('Walk me through the mechanics of why a stock deal is accretive when the acquirer''s P/E is higher than the target''s.', 'technical', 'hard', '{"ib"}', '{}'),
('If the target has a much higher growth rate than the acquirer, how might that change whether a stock deal is accretive?', 'technical', 'hard', '{"ib"}', '{}'),
('How would you set up a basic LBO model, and what are the two or three assumptions that move the returns the most?', 'technical', 'hard', '{"ib"}', '{}'),
('Rank the entry multiple, exit multiple, and leverage level by how much they typically drive LBO returns, and explain why.', 'technical', 'hard', '{"ib"}', '{}'),
('If you could only stress-test one assumption in an LBO model before presenting it, which would it be and why?', 'technical', 'hard', '{"ib"}', '{}'),
('Explain how a Deferred Tax Liability gets created in an M&A deal, and why it matters for the model.', 'technical', 'hard', '{"ib"}', '{}'),
('Walk me through why a step-up in asset basis in an acquisition creates a Deferred Tax Liability.', 'technical', 'hard', '{"ib"}', '{}'),
('How does the presence of a DTL affect the Purchase Price Allocation in a merger model?', 'technical', 'hard', '{"ib"}', '{}'),
('Would you rather maximize IRR or the money-on-money multiple on a deal, and why might those two goals conflict?', 'technical', 'hard', '{"ib"}', '{}'),
('Explain a scenario where a shorter holding period boosts IRR but hurts the total multiple returned.', 'technical', 'hard', '{"ib"}', '{}'),
('Why might a private equity fund prioritize IRR over MoM even when MoM is what limited partners ultimately care about?', 'technical', 'hard', '{"ib"}', '{}'),
('Walk me through how a change in working capital flows into a cash flow statement and why it matters for a DCF.', 'technical', 'hard', '{"ib"}', '{}'),
('If a company''s working capital needs increase as it grows, how does that affect its Free Cash Flow projections?', 'technical', 'hard', '{"ib"}', '{}'),
('Explain why an increase in Accounts Receivable is treated as a use of cash even though it represents revenue already earned.', 'technical', 'hard', '{"ib"}', '{}'),
('How would you decide between using the Public Comps and the Precedent Transactions method if they gave you very different answers?', 'technical', 'hard', '{"ib"}', '{}'),
('Precedent Transactions typically imply a higher value than Public Comps — explain why, and how you''d reconcile the two in a final valuation range.', 'technical', 'hard', '{"ib"}', '{}'),
('If your DCF, Comps, and Precedent Transactions all suggest meaningfully different values, walk me through how you''d present that range to a client.', 'technical', 'hard', '{"ib"}', '{}'),
('Why private equity instead of investment banking?', 'behavioral', 'easy', '{"pe"}', '{}'),
('What draws you to the investing side of the business rather than advisory work?', 'behavioral', 'easy', '{"pe"}', '{}'),
('Why do you want to sit on the buy-side rather than working deals from the sell-side?', 'behavioral', 'easy', '{"pe"}', '{}'),
('Walk me through your resume with an eye toward what''s led you to investing.', 'behavioral', 'easy', '{"pe"}', '{}'),
('Take me through your background and connect the dots to why you want to be an investor.', 'behavioral', 'easy', '{"pe"}', '{}'),
('What in your experience so far points toward a career evaluating and owning businesses?', 'behavioral', 'easy', '{"pe"}', '{}'),
('What kind of businesses or industries genuinely interest you as an investor, and why?', 'behavioral', 'easy', '{"pe"}', '{}'),
('If you could only invest in one sector for the next decade, which would it be and why?', 'behavioral', 'easy', '{"pe"}', '{}'),
('What types of companies do you find yourself paying attention to outside of work?', 'behavioral', 'easy', '{"pe"}', '{}'),
('Tell me about a company — public or private — you''d want to invest in, and make the case for it.', 'behavioral', 'medium', '{"pe"}', '{}'),
('Pick a business you admire and walk me through why it would make a good investment.', 'behavioral', 'medium', '{"pe"}', '{}'),
('Name a company you think is undervalued right now and defend your view.', 'behavioral', 'medium', '{"pe"}', '{}'),
('Describe a time you had to make a decision without complete information. How did you handle the risk?', 'behavioral', 'medium', '{"pe"}', '{}'),
('Tell me about weighing a decision where the data you had was incomplete or unreliable.', 'behavioral', 'medium', '{"pe"}', '{}'),
('Walk me through a call you had to make with real uncertainty attached to it.', 'behavioral', 'medium', '{"pe"}', '{}'),
('Walk me through a deal, internship project, or case study where you had to evaluate whether something was actually a good investment.', 'behavioral', 'medium', '{"pe"}', '{}'),
('Describe the most rigorous investment analysis you''ve done, even informally.', 'behavioral', 'medium', '{"pe"}', '{}'),
('Tell me about a time you dug into a company''s numbers to decide if it was worth backing.', 'behavioral', 'medium', '{"pe"}', '{}'),
('How do you spend your time outside of work, and how does that inform how you think about businesses?', 'behavioral', 'medium', '{"pe"}', '{}'),
('What do your hobbies or interests reveal about how you evaluate opportunities?', 'behavioral', 'medium', '{"pe"}', '{}'),
('Tell me about something you follow closely outside work that shapes your investing instincts.', 'behavioral', 'medium', '{"pe"}', '{}'),
('Pitch me a stock or a private business as if you were pitching a fund''s investment committee, in two minutes.', 'behavioral', 'hard', '{"pe"}', '{}'),
('Give me a two-minute investment pitch, including the risk to your thesis.', 'behavioral', 'hard', '{"pe"}', '{}'),
('Walk me through an investment case complete with your entry point, thesis, and exit plan.', 'behavioral', 'hard', '{"pe"}', '{}'),
('Tell me about a time your initial read on an opportunity turned out to be wrong. What did you miss?', 'behavioral', 'hard', '{"pe"}', '{}'),
('Describe an investment idea you were excited about that fell apart on closer inspection.', 'behavioral', 'hard', '{"pe"}', '{}'),
('Walk me through a case where your first instinct about a company was wrong, and what corrected it.', 'behavioral', 'hard', '{"pe"}', '{}'),
('If you had $50,000 of your own money to invest in one company right now, what would it be and why?', 'behavioral', 'hard', '{"pe"}', '{}'),
('If you had to put your own savings behind one business today, which would it be and why?', 'behavioral', 'hard', '{"pe"}', '{}'),
('Name one investment you''d personally make right now and defend it under pushback.', 'behavioral', 'hard', '{"pe"}', '{}'),
('Walk me through a disagreement you had with a manager or supervisor about how to evaluate a decision.', 'behavioral', 'hard', '{"pe"}', '{}'),
('Tell me about a time you and someone senior to you saw a decision completely differently.', 'behavioral', 'hard', '{"pe"}', '{}'),
('Describe pushing back on a superior''s judgment about whether something was worth pursuing.', 'behavioral', 'hard', '{"pe"}', '{}'),
('What is a leveraged buyout, in your own words, and why does using debt make sense for the buyer?', 'technical', 'easy', '{"pe"}', '{}'),
('Explain an LBO to someone with no finance background, focusing on why debt is part of the strategy.', 'technical', 'easy', '{"pe"}', '{}'),
('Why would a firm choose to fund an acquisition with debt instead of just using its own cash?', 'technical', 'easy', '{"pe"}', '{}'),
('What makes a company a good candidate for an LBO?', 'technical', 'easy', '{"pe"}', '{}'),
('List the characteristics that make a business attractive to a leveraged buyer.', 'technical', 'easy', '{"pe"}', '{}'),
('Why do private equity firms tend to favor stable, cash-generative businesses for buyouts?', 'technical', 'easy', '{"pe"}', '{}'),
('What''s the difference between a strategic buyer and a financial sponsor in an acquisition?', 'technical', 'easy', '{"pe"}', '{}'),
('Explain how a strategic acquirer''s motivations differ from a private equity firm''s.', 'technical', 'easy', '{"pe"}', '{}'),
('Why might a strategic buyer be willing to pay more for the same target than a financial sponsor?', 'technical', 'easy', '{"pe"}', '{}'),
('Walk me through the basic mechanics of an LBO model — what goes in, and what comes out.', 'technical', 'medium', '{"pe"}', '{}'),
('Describe the core inputs and outputs of an LBO model at a high level.', 'technical', 'medium', '{"pe"}', '{}'),
('If you had five minutes to explain an LBO model''s structure, what would you cover?', 'technical', 'medium', '{"pe"}', '{}'),
('What levers can a private equity firm pull during its hold period to increase its returns?', 'technical', 'medium', '{"pe"}', '{}'),
('Beyond paying down debt, what actions can a sponsor take to grow returns during ownership?', 'technical', 'medium', '{"pe"}', '{}'),
('Name three ways a fund can improve a portfolio company''s performance before exit.', 'technical', 'medium', '{"pe"}', '{}'),
('What''s the difference between the entry multiple and the exit multiple, and why do funds care about the spread?', 'technical', 'medium', '{"pe"}', '{}'),
('Explain why multiple expansion matters to a private equity return, separate from operational improvement.', 'technical', 'medium', '{"pe"}', '{}'),
('If the entry and exit multiples are identical, where does the fund''s return actually come from?', 'technical', 'medium', '{"pe"}', '{}'),
('Explain how a revolver is used in an LBO model and when a company would draw on it.', 'technical', 'medium', '{"pe"}', '{}'),
('Walk me through why a portfolio company might need a revolving credit facility during a downturn.', 'technical', 'medium', '{"pe"}', '{}'),
('What role does a revolver play in managing a company''s short-term cash needs post-buyout?', 'technical', 'medium', '{"pe"}', '{}'),
('What kinds of debt might a sponsor use to finance a buyout, and how do they differ in risk and cost?', 'technical', 'medium', '{"pe"}', '{}'),
('Compare senior debt and subordinated debt in an LBO capital structure.', 'technical', 'medium', '{"pe"}', '{}'),
('Walk me through the debt tranches in a typical buyout, from cheapest to most expensive.', 'technical', 'medium', '{"pe"}', '{}'),
('A fund buys a company at 8x EBITDA, holds it five years, and exits at 8x EBITDA with no multiple expansion. Where does the return come from?', 'technical', 'hard', '{"pe"}', '{}'),
('If entry and exit multiples are flat, break down the return purely into debt paydown and EBITDA growth.', 'technical', 'hard', '{"pe"}', '{}'),
('Walk me through decomposing an LBO''s IRR into its component drivers when there''s no multiple expansion.', 'technical', 'hard', '{"pe"}', '{}'),
('How would you set up the mandatory versus optional debt paydown in an LBO model?', 'technical', 'hard', '{"pe"}', '{}'),
('Explain the difference between a cash sweep and scheduled amortization in an LBO model.', 'technical', 'hard', '{"pe"}', '{}'),
('Walk me through how excess cash flow gets allocated to debt paydown in a typical LBO structure.', 'technical', 'hard', '{"pe"}', '{}'),
('Walk me through how you''d decide between a dividend recap and an early exit for a portfolio company that''s performing well.', 'technical', 'hard', '{"pe"}', '{}'),
('Compare the trade-offs of recapitalizing a strong-performing portfolio company versus selling it early.', 'technical', 'hard', '{"pe"}', '{}'),
('If a portfolio company is outperforming, what factors would push a fund toward a dividend recap instead of a sale?', 'technical', 'hard', '{"pe"}', '{}'),
('What''s the difference between maximizing IRR and maximizing MoM, and how would a 3-year hold versus a 7-year hold change which one you optimize for?', 'technical', 'hard', '{"pe"}', '{}'),
('Explain a scenario where a fund would knowingly sacrifice IRR to protect its money-on-money multiple.', 'technical', 'hard', '{"pe"}', '{}'),
('Why might a shorter hold period inflate IRR while actually delivering a worse total return to investors?', 'technical', 'hard', '{"pe"}', '{}'),
('How does an add-on acquisition inside an existing portfolio company change the return profile of the original deal?', 'technical', 'hard', '{"pe"}', '{}'),
('Walk me through how bolt-on acquisitions can boost a platform company''s exit multiple.', 'technical', 'hard', '{"pe"}', '{}'),
('Explain how buying smaller companies into a larger portfolio platform creates value beyond simple EBITDA addition.', 'technical', 'hard', '{"pe"}', '{}'),
('Why consulting, specifically, over other career paths?', 'behavioral', 'easy', '{"consulting"}', '{}'),
('What makes consulting the right fit for you compared to industry or finance roles?', 'behavioral', 'easy', '{"consulting"}', '{}'),
('Of everything you could be doing, why does consulting appeal to you most?', 'behavioral', 'easy', '{"consulting"}', '{}'),
('Why this firm, and not one of its direct competitors?', 'behavioral', 'easy', '{"consulting"}', '{}'),
('What set us apart from the other firms you''re considering?', 'behavioral', 'easy', '{"consulting"}', '{}'),
('What made you prioritize applying here specifically?', 'behavioral', 'easy', '{"consulting"}', '{}'),
('Walk me through your resume with a consulting lens — what story does it tell?', 'behavioral', 'easy', '{"consulting"}', '{}'),
('Take me through your background and connect it to the skills consulting requires.', 'behavioral', 'easy', '{"consulting"}', '{}'),
('Summarize your resume in a way that makes the case for you as a consultant.', 'behavioral', 'easy', '{"consulting"}', '{}'),
('Tell me about a time you had to change someone''s mind about a decision they''d already made.', 'behavioral', 'medium', '{"consulting"}', '{}'),
('Describe convincing someone to reverse a call they were fairly confident in.', 'behavioral', 'medium', '{"consulting"}', '{}'),
('Walk me through persuading a skeptical stakeholder to see things your way.', 'behavioral', 'medium', '{"consulting"}', '{}'),
('Describe a time you had to lead a project without any formal authority over the people involved.', 'behavioral', 'medium', '{"consulting"}', '{}'),
('Tell me about driving a group toward a deadline when you had no actual power over them.', 'behavioral', 'medium', '{"consulting"}', '{}'),
('Walk me through getting people to follow your lead without a title to back it up.', 'behavioral', 'medium', '{"consulting"}', '{}'),
('Tell me about a time you had to resolve a disagreement within a team you were part of.', 'behavioral', 'medium', '{"consulting"}', '{}'),
('Describe stepping into the middle of a conflict between two teammates.', 'behavioral', 'medium', '{"consulting"}', '{}'),
('Walk me through mediating a dispute that was slowing your team down.', 'behavioral', 'medium', '{"consulting"}', '{}'),
('Walk me through your greatest achievement, and why it matters to you.', 'behavioral', 'medium', '{"consulting"}', '{}'),
('What''s the accomplishment you''re proudest of, and what made it hard to pull off?', 'behavioral', 'medium', '{"consulting"}', '{}'),
('Tell me about the moment in your career or education you''d point to as your biggest win.', 'behavioral', 'medium', '{"consulting"}', '{}'),
('Tell me about the biggest professional obstacle you''ve faced, and what you''d do differently if you hit it again.', 'behavioral', 'hard', '{"consulting"}', '{}'),
('Describe the hardest professional setback you''ve had and what you learned that would change your approach next time.', 'behavioral', 'hard', '{"consulting"}', '{}'),
('Walk me through the toughest thing you''ve had to overcome at work or school, in detail.', 'behavioral', 'hard', '{"consulting"}', '{}'),
('Describe a time you had to deliver a recommendation you knew the client or stakeholder didn''t want to hear.', 'behavioral', 'hard', '{"consulting"}', '{}'),
('Tell me about presenting an unwelcome conclusion to someone who was hoping for a different answer.', 'behavioral', 'hard', '{"consulting"}', '{}'),
('Walk me through defending an unpopular recommendation under direct pushback.', 'behavioral', 'hard', '{"consulting"}', '{}'),
('Tell me about a time a project you led went off the rails. What did you do, and what happened?', 'behavioral', 'hard', '{"consulting"}', '{}'),
('Describe a project under your ownership that started falling apart, and your response in real time.', 'behavioral', 'hard', '{"consulting"}', '{}'),
('Walk me through a leadership situation that went badly and what you did to recover it.', 'behavioral', 'hard', '{"consulting"}', '{}'),
('Walk me through a time you had to influence a decision where you had no positional power over the outcome.', 'behavioral', 'hard', '{"consulting"}', '{}'),
('Describe getting buy-in from people who had no obligation to listen to you.', 'behavioral', 'hard', '{"consulting"}', '{}'),
('Tell me about shaping an outcome you technically had no authority over.', 'behavioral', 'hard', '{"consulting"}', '{}'),
('How many gas stations do you think there are in Chicago?', 'technical', 'easy', '{"consulting"}', '{}'),
('Estimate the number of gas stations in a city roughly the size of Chicago.', 'technical', 'easy', '{"consulting"}', '{}'),
('How would you go about estimating the number of gas stations in a major U.S. city?', 'technical', 'easy', '{"consulting"}', '{}'),
('Estimate how many pizzas are sold in your hometown in a given month.', 'technical', 'easy', '{"consulting"}', '{}'),
('How many pizzas would you guess get sold in a mid-sized city over the course of a year?', 'technical', 'easy', '{"consulting"}', '{}'),
('Walk me through estimating monthly pizza sales for a city of about 500,000 people.', 'technical', 'easy', '{"consulting"}', '{}'),
('How would you structure your approach before you even start estimating a market size?', 'technical', 'easy', '{"consulting"}', '{}'),
('Before crunching any numbers, what framework would you lay out for a market-sizing question?', 'technical', 'easy', '{"consulting"}', '{}'),
('What''s the first thing you''d clarify with the interviewer before attempting a sizing estimate?', 'technical', 'easy', '{"consulting"}', '{}'),
('Estimate the annual market size for bottled water in the United States.', 'technical', 'medium', '{"consulting"}', '{}'),
('Size the U.S. market for bottled water and walk me through your assumptions.', 'technical', 'medium', '{"consulting"}', '{}'),
('Estimate how much U.S. consumers spend annually on bottled water.', 'technical', 'medium', '{"consulting"}', '{}'),
('A client''s revenue is flat year-over-year despite steady unit sales growth. What are the first three things you''d check?', 'technical', 'medium', '{"consulting"}', '{}'),
('Revenue is stagnant even as volume grows — what hypotheses would you test first?', 'technical', 'medium', '{"consulting"}', '{}'),
('Walk me through diagnosing why sales volume is up but total revenue hasn''t moved.', 'technical', 'medium', '{"consulting"}', '{}'),
('Estimate how many dentists are currently practicing in a mid-sized country of your choosing.', 'technical', 'medium', '{"consulting"}', '{}'),
('Pick a country and estimate the number of practicing dentists there.', 'technical', 'medium', '{"consulting"}', '{}'),
('Walk me through sizing the number of dental practices in a country of about 30 million people.', 'technical', 'medium', '{"consulting"}', '{}'),
('Walk me through how you''d size the market for electric bikes in a major U.S. city.', 'technical', 'medium', '{"consulting"}', '{}'),
('Estimate annual electric bike sales in a city like Austin or Denver.', 'technical', 'medium', '{"consulting"}', '{}'),
('Size the addressable market for e-bikes in a mid-sized American city, and state your assumptions.', 'technical', 'medium', '{"consulting"}', '{}'),
('A retail client''s profits are declining even though revenue is growing. Walk me through how you''d diagnose the cause.', 'technical', 'hard', '{"consulting"}', '{}'),
('Revenue is up but margins are shrinking — walk me through the hypotheses you''d test with the client.', 'technical', 'hard', '{"consulting"}', '{}'),
('A retailer''s top line looks healthy but profitability is falling. What''s your structured approach to finding out why?', 'technical', 'hard', '{"consulting"}', '{}'),
('Estimate the total addressable market for at-home fitness equipment in Western Europe, and state your key assumptions out loud.', 'technical', 'hard', '{"consulting"}', '{}'),
('Size the market opportunity for home fitness equipment across a region like Western Europe.', 'technical', 'hard', '{"consulting"}', '{}'),
('Walk me through estimating the TAM for connected fitness products in a handful of European countries.', 'technical', 'hard', '{"consulting"}', '{}'),
('A client wants to know whether they should enter a new international market. What framework would you use, and what would you ask for first?', 'technical', 'hard', '{"consulting"}', '{}'),
('Walk me through advising a client on market entry into a new country, starting with what data you''d request.', 'technical', 'hard', '{"consulting"}', '{}'),
('A company is considering expanding into a new geography — what''s your structured approach to evaluating the decision?', 'technical', 'hard', '{"consulting"}', '{}'),
('Walk me through how you''d size the market for a subscription meal-kit service in a country with no publicly available industry data.', 'technical', 'hard', '{"consulting"}', '{}'),
('Estimate the market for a subscription meal-kit business in a market where you can''t rely on published industry reports.', 'technical', 'hard', '{"consulting"}', '{}'),
('How would you approach sizing a niche subscription business in a country with limited public data availability?', 'technical', 'hard', '{"consulting"}', '{}');