-- Expands the question bank substantially and adds weighted random
-- selection so common/general behavioral questions surface more often
-- than rare "brain game" curveball ones.

alter table public.questions add column weight integer not null default 10;

-- Lower the weight on the existing curveball-style hard questions --
-- fun to see occasionally, but shouldn't dominate hard mode.
update public.questions set weight = 3
where text in (
  'Name 10 things you could use a pencil for that aren''t writing.',
  'Sell me this stapler in 60 seconds.',
  'If you were a kitchen appliance, which one would you be and why?',
  'You have 60 seconds: convince me the office should switch to a 4-day work week.',
  'Name as many uses as you can for a paperclip in one minute.',
  'If you could only ask one question to figure out if someone would be a great hire, what would it be?'
);

insert into public.questions (text, category, difficulty, industries, weight) values
-- Easy (more general warm-up questions)
('What attracted you to this specific group or team?', 'behavioral', 'easy', '{general}', 10),
('What''s a hobby or interest that says something about how you work?', 'behavioral', 'easy', '{general}', 10),
('What''s the last book, article, or podcast that changed how you think about business?', 'behavioral', 'easy', '{general}', 10),
('How do you typically prepare before a big meeting or presentation?', 'behavioral', 'easy', '{general}', 10),
('What''s something about your background that isn''t on your resume?', 'behavioral', 'easy', '{general}', 10),
('What do you like to do to unwind outside of work?', 'behavioral', 'easy', '{general}', 10),
('What''s a skill you''re currently trying to build?', 'behavioral', 'easy', '{general}', 10),
('Tell me about a mentor who''s shaped how you think about your career.', 'behavioral', 'easy', '{general}', 10),
('What was your first job, and what did you learn from it?', 'behavioral', 'easy', '{general}', 10),
('How do you stay organized when you have a lot going on?', 'behavioral', 'easy', '{general}', 10),
('What''s a goal you''re working toward right now?', 'behavioral', 'easy', '{general}', 10),
('What do you think will be the biggest change in this industry over the next five years?', 'behavioral', 'easy', '{general}', 10),
('Why should we pick you over another candidate with a similar background?', 'behavioral', 'easy', '{general}', 10),
('What''s something most people don''t know about you?', 'behavioral', 'easy', '{general}', 10),
('How did you spend your last summer?', 'behavioral', 'easy', '{general}', 10),
('What extracurricular or club activity are you most proud of?', 'behavioral', 'easy', '{general}', 10),
('What''s a habit that''s helped you succeed?', 'behavioral', 'easy', '{general}', 10),
('Tell me about a class that was harder than you expected.', 'behavioral', 'easy', '{general}', 10),
('What made you choose your school or major?', 'behavioral', 'easy', '{general}', 10),
('What''s your favorite way to learn something new?', 'behavioral', 'easy', '{general}', 10),
('Describe your ideal work environment.', 'behavioral', 'easy', '{general}', 10),
('What''s a recent accomplishment you''re proud of?', 'behavioral', 'easy', '{general}', 10),
('How do you typically handle a slow, uneventful day at work?', 'behavioral', 'easy', '{general}', 10),
('What do you do to keep up with industry news?', 'behavioral', 'easy', '{general}', 10),
('Tell me about a time you had free time and chose to use it productively.', 'behavioral', 'easy', '{general}', 10),
('What''s the most interesting thing you''ve read about this industry recently?', 'behavioral', 'easy', '{general}', 10),
('Why do you think you''ll enjoy this specific type of work day-to-day?', 'behavioral', 'easy', '{general}', 10),
('What''s something you do outside of school or work that requires discipline?', 'behavioral', 'easy', '{general}', 10),
('If you got this offer today, what would you do to prepare before starting?', 'behavioral', 'easy', '{general}', 10),
('What''s a question you wish more interviewers asked?', 'behavioral', 'easy', '{general}', 10),
-- Medium (more STAR-format behavioral)
('Tell me about a time you had to build a relationship with someone very different from you.', 'behavioral', 'medium', '{general}', 10),
('Describe a time you spotted a problem before anyone else did.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time you had to work with limited resources.', 'behavioral', 'medium', '{general}', 10),
('Describe a time you disagreed with your boss and had to raise it.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time a project''s scope changed midway through. How did you adjust?', 'behavioral', 'medium', '{general}', 10),
('Describe a time you had to motivate a team that had lost momentum.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time you caught a mistake someone else made.', 'behavioral', 'medium', '{general}', 10),
('Describe a time you had to say something unpopular in a group setting.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time you were the least experienced person in the room.', 'behavioral', 'medium', '{general}', 10),
('Describe a time your instincts turned out to be wrong.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time you had to build trust with a new team quickly.', 'behavioral', 'medium', '{general}', 10),
('Describe a time you had to balance speed against accuracy.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time you volunteered for something outside your usual responsibilities.', 'behavioral', 'medium', '{general}', 10),
('Describe a time a plan fell apart and you had to improvise.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time you worked toward a goal you personally didn''t fully believe in.', 'behavioral', 'medium', '{general}', 10),
('Describe a time you had to hold someone accountable.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time you managed up -- influenced someone more senior than you.', 'behavioral', 'medium', '{general}', 10),
('Describe a time you had to deliver results with very little guidance.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time you asked for help when you needed it.', 'behavioral', 'medium', '{general}', 10),
('Describe a time you had to switch strategies partway through a project.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time communication broke down within your team.', 'behavioral', 'medium', '{general}', 10),
('Describe a time you exceeded a goal you were given.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time you had to defend your work to a skeptical audience.', 'behavioral', 'medium', '{general}', 10),
('Describe a time you took on a leadership role you weren''t officially given.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time you had to stay calm under real pressure.', 'behavioral', 'medium', '{general}', 10),
('Describe a time you had to work through a conflict between two other people.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time you set a goal for yourself and didn''t hit it.', 'behavioral', 'medium', '{general}', 10),
('Describe a time you had to onboard or train someone.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time you had to make a tradeoff between two good options.', 'behavioral', 'medium', '{general}', 10),
('Describe a time you received credit you felt you didn''t fully deserve.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time you had to work with someone in a different time zone or location.', 'behavioral', 'medium', '{general}', 10),
('Describe a time you had to unlearn something you thought you knew.', 'behavioral', 'medium', '{general}', 10),
('Tell me about a time your work didn''t get the recognition you expected.', 'behavioral', 'medium', '{general}', 10),
('Describe a time you had to push back on a client or stakeholder request.', 'behavioral', 'medium', '{ib,consulting,pe}', 10),
('Tell me about a time you noticed a process that could be improved and did something about it.', 'behavioral', 'medium', '{general}', 10),
-- Hard: tough self-critical (normal weight)
('What''s a project you''re privately not that proud of?', 'behavioral', 'hard', '{general}', 10),
('If you had to rank your last three internships or jobs from best to worst, where would this kind of work fall, and why?', 'behavioral', 'hard', '{general}', 10),
('What''s the biggest gap between how you see yourself and how others see you?', 'behavioral', 'hard', '{general}', 10),
('Tell me about a time you were the reason something went wrong.', 'behavioral', 'hard', '{general}', 10),
('What feedback have you gotten more than once that you still haven''t fully fixed?', 'behavioral', 'hard', '{general}', 10),
('If we hired you and it didn''t work out, what would most likely be the reason?', 'behavioral', 'hard', '{general}', 10),
('Tell me about a time your work ethic actually worked against you.', 'behavioral', 'hard', '{general}', 10),
('Describe the moment you felt most out of your depth professionally.', 'behavioral', 'hard', '{general}', 10),
('What''s something you said in a past interview that you''d answer differently today?', 'behavioral', 'hard', '{general}', 10),
('Tell me about a time you avoided a hard conversation you should have had.', 'behavioral', 'hard', '{general}', 10),
-- Hard: curveball / creative (low weight, rare)
('If you had to teach a five-year-old what this job actually does, how would you explain it?', 'behavioral', 'hard', '{general}', 3),
('You''re stuck in an elevator with our CEO for 60 seconds. What do you say?', 'behavioral', 'hard', '{general}', 3),
('Estimate how many windows are in New York City. Walk me through your logic.', 'behavioral', 'hard', '{general}', 3),
('If our firm were an animal, what would it be and why?', 'behavioral', 'hard', '{general}', 3),
('Pitch me a business idea using only things visible in this room.', 'behavioral', 'hard', '{general}', 3),
('What''s a widely-held opinion in this industry that you think is actually wrong?', 'behavioral', 'hard', '{general}', 3),
('If you could swap jobs with anyone for a day, who would it be and why?', 'behavioral', 'hard', '{general}', 3),
('Describe your personality using only three emojis, then explain your choices.', 'behavioral', 'hard', '{general}', 3),
('You have 30 seconds: talk me through how you''d improve this interview process.', 'behavioral', 'hard', '{general}', 3),
('Sell me on why I should switch careers into this industry, in one minute.', 'behavioral', 'hard', '{general}', 3);
